In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
fbs = pd.read_csv("FoodBalanceSheets_E_Africa_NOFLAG.csv", encoding = 'latin-1')

In [3]:
#Area that had the highest sum in 2017?
area_sum = fbs.groupby("Area")["Y2017"].sum()
area_highest_sum = area_sum.idxmax()
highest_sum_value = area_sum.max()
area_highest_sum, highest_sum_value

('Nigeria', 1483268.23)

In [4]:
#Describtion of the dataset based on the year 2017
fbs1 = fbs["Y2017"].describe().round(2)
fbs1

count     59437.00
mean        140.92
std        1671.86
min       -1582.00
25%           0.00
50%           0.10
75%           9.00
max      190873.00
Name: Y2017, dtype: float64

In [5]:
#Least correlation
correlation_matrix = fbs.corr()
correlation_matrix

<ipython-input-5-727056edac00>:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_matrix = fbs.corr()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
Area Code,1.000000,-0.005159,-0.000209,0.006164,0.005472,0.005247,0.005006,0.005665
Item Code,-0.005159,1.000000,-0.024683,0.021722,0.020857,0.020109,0.021494,0.021314
Element Code,-0.000209,-0.024683,1.000000,0.024457,0.023889,0.023444,0.024254,0.024279
Y2014,0.006164,0.021722,0.024457,1.000000,0.994647,0.996081,0.995230,0.994872
Y2015,0.005472,0.020857,0.023889,0.994647,1.000000,0.995739,0.988048,0.988208
Y2016,0.005247,0.020109,0.023444,0.996081,0.995739,1.000000,0.992785,0.992757
Y2017,0.005006,0.021494,0.024254,0.995230,0.988048,0.992785,1.000000,0.998103
Y2018,0.005665,0.021314,0.024279,0.994872,0.988208,0.992757,0.998103,1.000000

In [6]:
y = [(2, 4), (7, 8), (1, 5, 9)]
x = y[1][1]
x

8

In [7]:
# Areas with the 7th lowest sum in 2017
Y2017_group = fbs.groupby('Area')['Y2017'].sum()
sorted_2017 = Y2017_group.sort_values(ascending=True)
sorted_2017.head(7)

Area
Sudan (former)               0.00
Ethiopia PDR                 0.00
Comoros                     59.84
Seychelles                 442.34
Sao Tome and Principe    12662.63
Cabo Verde               14650.74
Guinea-Bissau            19102.77
Name: Y2017, dtype: float64

In [8]:
#total number of the sum of Processing in 2017
fbs.groupby('Element')['Y2017'].sum()

Element
Domestic supply quantity                  2088198.10
Export Quantity                            182338.80
Fat supply quantity (g/capita/day)          10253.84
Feed                                       223705.68
Food                                      1258888.28
Food supply (kcal/capita/day)              454681.00
Food supply quantity (kg/capita/yr)         48690.04
Import Quantity                            294559.09
Losses                                     160614.00
Other uses (non-food)                       91645.97
Processing                                 292836.00
Production                                2030056.89
Protein supply quantity (g/capita/day)      11842.45
Residuals                                   35500.00
Seed                                        24870.14
Stock Variation                             54316.91
Total Population - Both sexes             1112641.00
Tourist consumption                            91.00
Name: Y2017, dtype: float64

In [9]:
# total sum of Wine produced in 2015 and 2018 respectively
fbs.groupby('Item')[['Y2015', 'Y2018']].sum()

                         Y2015      Y2018
Item
Alcohol, Non-Food      2180.00    2293.00
Alcoholic Beverages   98783.72   97847.27
Animal Products       11811.73   11578.61
Animal fats          200675.72  269648.27
Apples and products   10559.15    9640.51
...                        ...        ...
Vegetables, Other    158104.08  163987.21
Vegetal Products     107064.17  107775.39
Wheat and products   234710.51  242645.19
Wine                   4251.81    4039.32
Yams                 203151.78  221272.09

[119 rows x 2 columns]

In [10]:
#checking for missing values in my dataframe, focus on year 2014
fbs.isna().sum()
missing_Y2014 = fbs['Y2014'].isna().sum()
total_count = fbs['Y2014'].count() + missing_Y2014

#calculating the percentage of missing values
percentage_missing = (missing_Y2014 / total_count) * 100
round(percentage_missing, 3)

2.607

In [11]:
#getting protein supply quatity in 2015
madagascar_protein = fbs[(fbs['Area'] == 'Madagascar') & (fbs['Element'] == 'Protein supply quantity (g/capita/day)')]
Y2015_tot_qty = madagascar_protein['Y2015'].sum()
round(Y2015_tot_qty, 2)

173.05

In [12]:
#Tyoe of Error
my_tuppy = (1,2,5,8)

my_tuppy[2] = 6

TypeError: ignored

In [13]:
#Finding the output for this
S = [['him', 'sell'], [90, 28, 43]]

S[0][1][1]

'e'

In [14]:
fbs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60943 entries, 0 to 60942
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Area Code     60943 non-null  int64
 1   Area          60943 non-null  object
 2   Item Code     60943 non-null  int64
 3   Item          60943 non-null  object
 4   Element Code  60943 non-null  int64
 5   Element       60943 non-null  object
 6   Unit          60943 non-null  object
 7   Y2014         59354 non-null  float64
 8   Y2015         59395 non-null  float64
 9   Y2016         59408 non-null  float64
 10  Y2017         59437 non-null  float64
 11  Y2018         59507 non-null  float64
dtypes: float64(5), int64(3), object(4)
memory usage: 5.6+ MB

In [15]:
#year with the highest sum of Stock Variation?
fbs.groupby('Element')[['Y2014','Y2015','Y2016','Y2017','Y2018']].sum()

,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,
Domestic supply quantity,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),10225.56,10235.74,10102.77,10253.84,10258.69
Feed,216927.89,225050.22,228958.65,223705.68,233489.68
Food,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),78718.13,66254.41,69563.68,91645.97,91300.97
Processing,282923.00,287929.00,280631.00,292836.00,308429.00
Production,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,416.00,349.00,89.00,91.00,90.00

In [16]:
#total number of unique countries in the datase
len(fbs['Area'].unique())

49